from sqlalchemy import Column, Integer, String, Date, Text
from sqlalchemy.ext.declarative import declarative_base


from models.base import Base


class DDJJ(Base):
    __tablename__ = "ddjj"

    ddjj_id = Column(Integer, primary_key=True, autoincrement=True)
    login = Column(String(190))
    ddjj_fecha_ultimo_cambio = Column(String(20))
    ddjj_nombre = Column(String(64))
    ddjj_apellido = Column(String(64))
    ddjj_estado_civil = Column(String(64))
    ddjj_calle = Column(String(64))
    ddjj_depto = Column(String(64))
    ddjj_barrio = Column(String(64))
    ddjj_localidad = Column(String(64))
    ddjj_cp = Column(String(64))
    ddjj_provincia = Column(String(64))
    ddjj_calle_legal = Column(String(64))
    ddjj_depto_legal = Column(String(64))
    ddjj_barrio_legal = Column(String(64))
    ddjj_localidad_legal = Column(String(64))
    ddjj_cp_legal = Column(String(64))
    ddjj_provincia_legal = Column(String(64))
    ddjj_fecha_nac = Column(Date, nullable=True)  # fecha_nacimiento date
    ddjj_nacionalidad = Column(String(64))
    ddjj_sexo = Column(String(64))
    ddjj_correo_electronico = Column(String(64))
    ddjj_telefono = Column(String(64))
    ddjj_inscripto_programa_familias = Column(String(1))
    # Campos relacionados con hijos
    ddjj_hijo1_tiene = Column(String(1))
    ddjj_hijo1_nombre_completo = Column(String(64))
    ddjj_hijo1_estado_civil = Column(String(64))
    ddjj_hijo1_dni = Column(String(64))
    ddjj_hijo1_domicilio_real = Column(String(64))
    ddjj_hijo1_edad = Column(String(64))
    ddjj_hijo1_nacionalidad = Column(String(64))
    ddjj_hijo1_ocupacion = Column(String(64))
    ddjj_hijo1_convive_con_usted = Column(String(64))
    ddjj_hijo2_tiene = Column(String(1))
    ddjj_hijo2_nombre_completo = Column(String(64))
    ddjj_hijo2_estado_civil = Column(String(64))
    ddjj_hijo2_dni = Column(String(64))
    ddjj_hijo2_domicilio_real = Column(String(64))
    ddjj_hijo2_edad = Column(String(64))
    ddjj_hijo2_nacionalidad = Column(String(64))
    ddjj_hijo2_ocupacion = Column(String(64))
    ddjj_hijo2_convive_con_usted = Column(String(64))
    ddjj_hijo3_tiene = Column(String(1))
    ddjj_hijo3_nombre_completo = Column(String(64))
    ddjj_hijo3_estado_civil = Column(String(64))
    ddjj_hijo3_dni = Column(String(64))
    ddjj_hijo3_domicilio_real = Column(String(64))
    ddjj_hijo3_edad = Column(String(64))
    ddjj_hijo3_nacionalidad = Column(String(64))
    ddjj_hijo3_ocupacion = Column(String(64))
    ddjj_hijo3_convive_con_usted = Column(String(64))
    ddjj_hijo4_tiene = Column(String(1))
    ddjj_hijo4_nombre_completo = Column(String(64))
    ddjj_hijo4_estado_civil = Column(String(64))
    ddjj_hijo4_dni = Column(String(64))
    ddjj_hijo4_domicilio_real = Column(String(64))
    ddjj_hijo4_edad = Column(String(64))
    ddjj_hijo4_nacionalidad = Column(String(64))
    ddjj_hijo4_ocupacion = Column(String(64))
    ddjj_hijo4_convive_con_usted = Column(String(64))
    ddjj_hijo5_tiene = Column(String(1))
    ddjj_hijo5_nombre_completo = Column(String(64))
    ddjj_hijo5_estado_civil = Column(String(64))
    ddjj_hijo5_dni = Column(String(64))
    ddjj_hijo5_domicilio_real = Column(String(64))
    ddjj_hijo5_edad = Column(String(64))
    ddjj_hijo5_nacionalidad = Column(String(64))
    ddjj_hijo5_ocupacion = Column(String(64))
    ddjj_hijo5_convive_con_usted = Column(String(64))
    # Campos relacionados con otros y apoyos
    ddjj_otro1_tiene = Column(String(1))
    ddjj_otro1_nombre_completo = Column(String(64))
    ddjj_otro1_estado_civil = Column(String(64))
    ddjj_otro1_dni = Column(String(64))
    ddjj_otro1_domicilio_real = Column(String(64))
    ddjj_otro1_nacionalidad = Column(String(64))
    ddjj_otro1_edad = Column(String(64))
    ddjj_otro1_ocupacion = Column(String(64))
    ddjj_otro1_convive_con_usted = Column(String(64))
    ddjj_otro2_tiene = Column(String(1))
    ddjj_otro2_nombre_completo = Column(String(64))
    ddjj_otro2_estado_civil = Column(String(64))
    ddjj_otro2_dni = Column(String(64))
    ddjj_otro2_domicilio_real = Column(String(64))
    ddjj_otro2_nacionalidad = Column(String(64))
    ddjj_otro2_edad = Column(String(64))
    ddjj_otro2_ocupacion = Column(String(64))
    ddjj_otro2_convive_con_usted = Column(String(64))
    ddjj_otro3_tiene = Column(String(1))
    ddjj_otro3_nombre_completo = Column(String(64))
    ddjj_otro3_estado_civil = Column(String(64))
    ddjj_otro3_dni = Column(String(64))
    ddjj_otro3_domicilio_real = Column(String(64))
    ddjj_otro3_nacionalidad = Column(String(64))
    ddjj_otro3_edad = Column(String(64))
    ddjj_otro3_ocupacion = Column(String(64))
    ddjj_otro3_convive_con_usted = Column(String(64))
    ddjj_otro4_tiene = Column(String(1))
    ddjj_otro4_nombre_completo = Column(String(64))
    ddjj_otro4_estado_civil = Column(String(64))
    ddjj_otro4_dni = Column(String(64))
    ddjj_otro4_domicilio_real = Column(String(64))
    ddjj_otro4_nacionalidad = Column(String(64))
    ddjj_otro4_edad = Column(String(64))
    ddjj_otro4_ocupacion = Column(String(64))
    ddjj_otro4_convive_con_usted = Column(String(64))
    ddjj_otro5_tiene = Column(String(1))
    ddjj_otro5_nombre_completo = Column(String(64))
    ddjj_otro5_estado_civil = Column(String(64))
    ddjj_otro5_dni = Column(String(64))
    ddjj_otro5_domicilio_real = Column(String(64))
    ddjj_otro5_nacionalidad = Column(String(64))
    ddjj_otro5_edad = Column(String(64))
    ddjj_otro5_ocupacion = Column(String(64))
    ddjj_otro5_convive_con_usted = Column(String(64))
    # Repetir para otro2, otro3, etc.
    ddjj_apoyo1_tiene = Column(String(1))
    ddjj_apoyo1_nombre_completo = Column(String(64))
    ddjj_apoyo1_estado_civil = Column(String(64))
    ddjj_apoyo1_dni = Column(String(64))
    ddjj_apoyo1_domicilio_real = Column(String(64))
    ddjj_apoyo1_nacionalidad = Column(String(64))
    ddjj_apoyo1_edad = Column(String(64))
    ddjj_apoyo1_ocupacion = Column(String(64))
    ddjj_apoyo1_convive_con_usted = Column(String(64))
    ddjj_apoyo2_tiene = Column(String(1))
    ddjj_apoyo2_nombre_completo = Column(String(64))
    ddjj_apoyo2_estado_civil = Column(String(64))
    ddjj_apoyo2_dni = Column(String(64))
    ddjj_apoyo2_domicilio_real = Column(String(64))
    ddjj_apoyo2_nacionalidad = Column(String(64))
    ddjj_apoyo2_edad = Column(String(64))
    ddjj_apoyo2_ocupacion = Column(String(64))
    ddjj_apoyo2_convive_con_usted = Column(String(64))
    # Otros campos
    ddjj_educativo_maximo = Column(String(64))
    ddjj_ocupacion = Column(String(64))
    ddjj_horas_semanales = Column(String(64))
    ddjj_ingreso_mensual = Column(String(64))
    ddjj_existe_otro_ingreso = Column(String(64))
    ddjj_ingreso_grupo_familiar = Column(String(64))
    ddjj_analizaron = Column(String(64))
    ddjj_horas_ocio = Column(String(64))
    ddjj_extra_laborales = Column(Text, nullable=True)
    ddjj_denunciado_violencia_familiar = Column(String(64))
    ddjj_descripcion_violencia_familiar = Column(String(255))
    # Subregistros
    ddjj_causa_penal = Column(String(64))
    ddjj_descripcion_causa_penal = Column(String(255))
    ddjj_juicios_filiacion = Column(String(64))
    ddjj_descripcion_juicios_filiacion = Column(String(255))
    ddjj_subregistro_1 = Column(String(1))
    ddjj_subregistro_2 = Column(String(1))
    ddjj_subregistro_3 = Column(String(1))
    ddjj_subregistro_4 = Column(String(1))
    ddjj_subregistro_5_a = Column(String(1))
    ddjj_subregistro_5_b = Column(String(1))
    ddjj_subregistro_5_c = Column(String(1))
    ddjj_subregistro_6_a = Column(String(1))
    ddjj_subregistro_6_b = Column(String(1))
    ddjj_subregistro_6_c = Column(String(1))
    ddjj_subregistro_6_d = Column(String(1))
    ddjj_subregistro_6_2 = Column(String(1))
    ddjj_subregistro_6_3 = Column(String(1))
    ddjj_subregistro_6_mas_de_3 = Column(String(1))
    ddjj_subregistro_flexible = Column(String(1))
    ddjj_acepto_1 = Column(String(1))
    ddjj_acepto_2 = Column(String(1))
    ddjj_acepto_3 = Column(String(1))
    ddjj_acepto_4 = Column(String(1))
    ddjj_guardo_1 = Column(String(1), nullable=False, default="N")
    ddjj_guardo_2 = Column(String(1), nullable=False, default="N")
    ddjj_guardo_3 = Column(String(1), nullable=False, default="N")
    ddjj_guardo_4 = Column(String(1), nullable=False, default="N")
    ddjj_guardo_5 = Column(String(1), nullable=False, default="N")
    ddjj_guardo_6 = Column(String(1), nullable=False, default="N")
    ddjj_guardo_7 = Column(String(1), nullable=False, default="N")
    ddjj_guardo_8 = Column(String(1), nullable=False, default="N")

    # Campos nuevos ############

    # Flexibilidad edad (Subregistro general)
    ddjj_flex_edad_1 = Column(String(1))
    ddjj_flex_edad_2 = Column(String(1))
    ddjj_flex_edad_3 = Column(String(1))
    ddjj_flex_edad_4 = Column(String(1))
    ddjj_flex_edad_todos = Column(String(1))

    # Condiciones especiales: Discapacidad
    ddjj_discapacidad_1 = Column(String(1))  # sin necesidad de apoyos
    ddjj_discapacidad_2 = Column(String(1))  # con necesidad de apoyos

    ddjj_edad_discapacidad_0 = Column(String(1))  # 0 a 3
    ddjj_edad_discapacidad_1 = Column(String(1))  # 4 a 6
    ddjj_edad_discapacidad_2 = Column(String(1))  # 7 a 11
    ddjj_edad_discapacidad_3 = Column(String(1))  # 12 a 17
    ddjj_edad_discapacidad_4 = Column(String(1))  # 0 a 17

    # Condiciones especiales: Enfermedades
    ddjj_enfermedad_1 = Column(String(1))  # no afecta calidad de vida
    ddjj_enfermedad_2 = Column(String(1))  # afecta relativamente
    ddjj_enfermedad_3 = Column(String(1))  # afecta significativamente

    ddjj_edad_enfermedad_0 = Column(String(1))  # 0 a 3
    ddjj_edad_enfermedad_1 = Column(String(1))  # 4 a 6
    ddjj_edad_enfermedad_2 = Column(String(1))  # 7 a 11
    ddjj_edad_enfermedad_3 = Column(String(1))  # 12 a 17
    ddjj_edad_enfermedad_4 = Column(String(1))  # 0 a 17

    # Flexibilidad condiciones de salud
    ddjj_flex_condiciones_salud = Column(String(1))
    ddjj_flex_salud_edad_0 = Column(String(1))
    ddjj_flex_salud_edad_1 = Column(String(1))
    ddjj_flex_salud_edad_2 = Column(String(1))
    ddjj_flex_salud_edad_3 = Column(String(1))
    ddjj_flex_salud_edad_4 = Column(String(1))

    # Subregistro N°6: Grupo de hermanos
    ddjj_hermanos_comp_1 = Column(String(1))  # hasta 2
    ddjj_hermanos_comp_2 = Column(String(1))  # hasta 3
    ddjj_hermanos_comp_3 = Column(String(1))  # 4 o más

    ddjj_hermanos_edad_0 = Column(String(1))  # 0 a 6
    ddjj_hermanos_edad_1 = Column(String(1))  # 7 a 11
    ddjj_hermanos_edad_2 = Column(String(1))  # 12 a 17
    ddjj_hermanos_edad_3 = Column(String(1))  # 0 a 17

    ddjj_flex_hermanos_comp_1 = Column(String(1))
    ddjj_flex_hermanos_comp_2 = Column(String(1))
    ddjj_flex_hermanos_comp_3 = Column(String(1))

    ddjj_flex_hermanos_edad_0 = Column(String(1))
    ddjj_flex_hermanos_edad_1 = Column(String(1))
    ddjj_flex_hermanos_edad_2 = Column(String(1))
    ddjj_flex_hermanos_edad_3 = Column(String(1))

    # Los subregistros definitivos
    subreg_1 = Column(String(1))
    subreg_2 = Column(String(1))
    subreg_3 = Column(String(1))
    subreg_4 = Column(String(1))
    subreg_FE1 = Column(String(1))
    subreg_FE2 = Column(String(1))
    subreg_FE3 = Column(String(1))
    subreg_FE4 = Column(String(1))
    subreg_FET = Column(String(1))
    subreg_5A1E1 = Column(String(1))
    subreg_5A1E2 = Column(String(1))
    subreg_5A1E3 = Column(String(1))
    subreg_5A1E4 = Column(String(1))
    subreg_5A1ET = Column(String(1))
    subreg_5A2E1 = Column(String(1))
    subreg_5A2E2 = Column(String(1))
    subreg_5A2E3 = Column(String(1))
    subreg_5A2E4 = Column(String(1))
    subreg_5A2ET = Column(String(1))
    subreg_5B1E1 = Column(String(1))
    subreg_5B1E2 = Column(String(1))
    subreg_5B1E3 = Column(String(1))
    subreg_5B1E4 = Column(String(1))
    subreg_5B1ET = Column(String(1))
    subreg_5B2E1 = Column(String(1))
    subreg_5B2E2 = Column(String(1))
    subreg_5B2E3 = Column(String(1))
    subreg_5B2E4 = Column(String(1))
    subreg_5B2ET = Column(String(1))
    subreg_5B3E1 = Column(String(1))
    subreg_5B3E2 = Column(String(1))
    subreg_5B3E3 = Column(String(1))
    subreg_5B3E4 = Column(String(1))
    subreg_5B3ET = Column(String(1))
    subreg_F5E1 = Column(String(1))
    subreg_F5E2 = Column(String(1))
    subreg_F5E3 = Column(String(1))
    subreg_F5E4 = Column(String(1))
    subreg_F5ET = Column(String(1))
    subreg_61E1 = Column(String(1))
    subreg_61E2 = Column(String(1))
    subreg_61E3 = Column(String(1))
    subreg_61ET = Column(String(1))
    subreg_62E1 = Column(String(1))
    subreg_62E2 = Column(String(1))
    subreg_62E3 = Column(String(1))
    subreg_62ET = Column(String(1))
    subreg_63E1 = Column(String(1))
    subreg_63E2 = Column(String(1))
    subreg_63E3 = Column(String(1))
    subreg_63ET = Column(String(1))
    subreg_FQ1 = Column(String(1))
    subreg_FQ2 = Column(String(1))
    subreg_FQ3 = Column(String(1))
    subreg_F6E1 = Column(String(1))
    subreg_F6E2 = Column(String(1))
    subreg_F6E3 = Column(String(1))
    subreg_F6ET = Column(String(1))





